syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.routeguide";
option java_outer_classname = "RouteGuideProto";
option objc_class_prefix = "RTG";

package routeguide;

// Interface exported by the server.
service RouteGuide {
  /////////////////////////////////////////////////////////////////////////////
  // Codelab Hint: Define RPC methods here
  /////////////////////////////////////////////////////////////////////////////
}

message Point {
  /////////////////////////////////////////////////////////////////////////////
  // Codelab Hint: Define the Point messages here
  /////////////////////////////////////////////////////////////////////////////
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
message Feature {
  /////////////////////////////////////////////////////////////////////////////
  // Codelab Hint: Define the Feature messages here
  /////////////////////////////////////////////////////////////////////////////
}

// Not used in the RPC.  Instead, this is here for the form serialized to disk.
message FeatureDatabase {
  repeated Feature feature = 1;
}
